name: Publish OCI image

on:
  push:
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Push OCI image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: unmojang/drasl-test
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push OCI image
        env:
          REFERENCES: ${{ steps.meta.outputs.tags }}
        run: |
          for system in 'x86_64-linux' 'aarch64-linux'; do
            oci_archive="$(nix build --no-link --print-out-paths ".#oci-cross-$system")"

            for reference in $REFERENCES; do
              skopeo --insecure-policy copy \
                --dest-creds='${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}' \
                "docker-archive:$oci_archive" \
                "docker://$reference"
            done
          done
