name: nix build
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: unmojang
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build
      - run: nix build .#drasl-cross-aarch64-linux
      - run: nix flake check
